.PHONY: help install lock migrate revision run run-db stop-db create-user test test-cov

help:
	@echo "Available commands:"
	@echo "  lock         - Generate/update uv.lock file from pyproject.toml"
	@echo "  install      - Sync virtual environment with uv.lock (for dev)"
	@echo "  migrate      - Apply database migrations to the 'head' revision"
	@echo "  revision     - Create a new autogenerated migration file. Usage: make revision m=\"Your message\""
	@echo "  run-db       - Start PostgreSQL container using Docker Compose"
	@echo "  stop-db      - Stop PostgreSQL container"
	@echo "  run          - Run the development server"
	@echo "  create-user  - Create a new API user"
	@echo "  test         - Run unit and integration tests"
	@echo "  test-cov     - Run tests with coverage report"

# Генерация lock-файла
lock:
	@echo "Locking dependencies..."
	uv lock
	@echo "uv.lock file generated."

# Установка зависимостей с помощью uv sync
install:
	@echo "Syncing environment with uv.lock..."
	uv sync --all-extras
	@echo "Environment is up to date."

# Применение миграций
migrate:
	alembic upgrade head

# Создание новой миграции
revision:
	alembic revision --autogenerate -m "$(m)"

# Запустить БД
run-db:
	docker-compose up -d

# Остановить БД
stop-db:
	docker-compose down

# Запустить приложение
run:
	uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

# Создать нового пользователя API
create-user:
	@read -p "Enter username: " username; \
	python scripts/create_user.py $$username

# Запустить тесты
test:
	pytest

# Запустить тесты с отчетом о покрытии
test-cov:
	pytest --cov=app --cov-report=term-missing